REVOKE ALL PRIVILEGES ON DATABASE postgres FROM respondentsvc;
DROP SCHEMA IF EXISTS respondent CASCADE;
DROP ROLE IF EXISTS respondentsvc;

CREATE ROLE respondentsvc PASSWORD 'respondentsvc' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;

CREATE SCHEMA respondent AUTHORIZATION respondentsvc;

REVOKE ALL ON ALL TABLES IN SCHEMA respondent FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA respondent FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;

GRANT CONNECT ON DATABASE postgres TO respondentsvc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA respondent TO respondentsvc;
GRANT ALL ON ALL SEQUENCES IN SCHEMA respondent TO respondentsvc;
